(() => {
  'use strict';
  const activities = window.RETRIEVAL_ACTIVITIES;
  const main = document.querySelector('main');
  const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const paths = {
    book:'M10 10h13c4 0 5 2 5 5v26c-1-3-3-4-6-4H10z M28 15c0-3 2-5 5-5h7v27h-7c-3 0-4 1-5 4 M16 17h6 M16 23h6',
    write:'M12 8h20v9 M32 29v12H12V8 M18 34l2-8 15-15 6 6-15 15-8 2 M32 14l6 6 M16 38h12',
    check:'M10 10h28v31H10z M16 19l3 3 6-7 M28 19h5 M16 31l3 3 6-7 M28 31h5',
    calendar:'M9 12h30v28H9z M9 21h30 M17 8v8 M31 8v8 M17 28h3 M28 28h3 M17 34h3 M28 34h3',
    pair:'M12 17a5 5 0 1 0 10 0 5 5 0 1 0-10 0 M28 17a5 5 0 1 0 10 0 5 5 0 1 0-10 0 M9 37v-5c0-8 17-8 17 0v5 M25 28c6-4 16 0 16 5v4',
    two:'M9 10h12v28H9z M27 10h12v28H27z M15 18v12 M31 21c0-6 7-6 7-1 0 3-7 4-7 9h7',
    map:'M18 20h12v9H18z M5 7h12v8H5z M32 6h12v9H32z M5 36h12v8H5z M32 36h12v8H32z M17 14l5 6 M30 20l6-5 M22 29l-5 7 M30 29l6 7',
    columns:'M7 8h34v33H7z M24 8v33 M12 16h7 M29 16h7 M12 24h7 M29 24h7 M12 32h7 M29 32h7',
    grid:'M7 8h34v33H7z M7 19h34 M7 30h34 M18 8v33 M29 8v33',
    cards:'M8 14h23v29H8z M17 5h23v29h-5 M15 21h9 M15 27h9 M15 33h5',
    swap:'M8 17h30l-7-7 M38 31H8l7 7 M38 17v6 M8 31v-6',
    boards:'M6 10h36v24H6z M15 41l9-7 9 7 M15 18h18 M15 25h12',
    link:'M8 13h13v12H8z M28 24h13v12H28z M21 19c11 0-1 11 7 11 M23 29l5 1-1-5',
    picture:'M7 8h34v32H7z M7 32l12-12 8 8 6-6 8 10 M29 14a3 3 0 1 0 6 0 3 3 0 1 0-6 0',
    placemat:'M7 8h34v33H7z M18 19h12v11H18z M7 8l11 11 M41 8L30 19 M7 41l11-11 M41 41L30 30',
    dice:'M10 9h28v30H10z M17 16h1 M30 16h1 M23 24h1 M17 32h1 M30 32h1',
    clock:'M7 24a17 17 0 1 0 34 0 17 17 0 1 0-34 0 M24 7v34 M7 24h34 M24 24l11-11 M24 24l-11 11'
  };
  function icon(type){return `<svg class="icon" viewBox="0 0 48 48" aria-hidden="true"><path d="${paths[type] || paths.write}"/></svg>`;}
  document.querySelectorAll('[data-icon]').forEach(el => el.innerHTML=icon(el.dataset.icon));
  const key='tnt-retrieval-wheel-v1';
  function readSelection(){try{const value=JSON.parse(localStorage.getItem(key));if(Array.isArray(value))return new Set(value.filter(id=>activities.some(a=>a.id===id)));}catch{}return new Set(activities.map(a=>a.id));}
  let selected=readSelection();
  function saveSelection(){try{localStorage.setItem(key,JSON.stringify([...selected]));}catch{}}
  const chips=a=>`<div class="meta"><span class="chip">${a.minutes} min guide</span><span class="chip">${a.group}</span><span class="chip">${a.prep==='None'?'No prep':a.prep+' prep'}</span></div>`;
  const head=(title,description)=>`<section class="page-head"><p class="eyebrow">THE RETRIEVAL TOOLKIT</p><h1>${title}</h1><p class="lead">${description}</p></section>`;
  const downloadLinks=a=>`${['brain-dump','two-things','cops-and-robbers','challenge-grid','concept-map','retrieval-placemat','roll-and-retrieve','retrieval-clock'].includes(a.id)?`<a class="button secondary" href="./retrieval-${a.id}-template.docx?v=3" download>Word worksheet ↓</a>`:''}<a class="button secondary" href="./retrieval-${a.id}-template.pptx?v=3" download>PowerPoint template ↓</a>`;
  function card(a){return `<article class="activity-card">${icon(a.icon)}<h2><a href="./retrieval-${a.id}.html">${esc(a.name)}</a></h2><p>${esc(a.summary)}</p>${chips(a)}<p class="credit">${esc(a.credit)}</p><div class="card-bottom"><a href="./retrieval-${a.id}.html">How to run it ↗</a><label><input type="checkbox" data-select="${a.id}" ${selected.has(a.id)?'checked':''}> On wheel</label></div></article>`;}
  if(document.body.dataset.page==='activities'){
    main.innerHTML=head('Find your next retrieval activity.','Choose an approach that fits your time, grouping and preparation. Open a guide for visual steps, editable templates and sources.')+`<div class="filters"><label>Search activities<input id="search" type="search" placeholder="Try cards, recall or grid"></label><label>Time available<select id="time"><option value="99">Any length</option><option value="5">Up to 5 minutes</option><option value="8">Up to 8 minutes</option><option value="10">Up to 10 minutes</option></select></label><label>Grouping<select id="group"><option value="">Any grouping</option><option>Individual</option><option>Pairs / groups</option><option>Whole class</option></select></label><label>Preparation<select id="prep"><option value="">Any preparation</option><option value="None">No prep</option><option value="Low">Low prep</option><option value="Prepared">Prepared materials</option></select></label></div><div class="list-toolbar"><p id="count" class="muted" role="status"></p><div class="actions"><button class="secondary" id="reset">Reset filters</button><button class="secondary" id="use-filtered">Put these on the wheel</button><a class="button" href="./retrieval-wheel.html">Open wheel ↗</a></div></div><div id="cards" class="cards"></div><section class="template-section"><h2>Editable classroom templates</h2><p>Replace the bracketed text with your own taught content. Word worksheets suit written recall; PowerPoint templates suit whole-class display. Templates are unbranded. PowerPoint notes include setup and checking guidance; source credits are on the activity pages.</p><div class="download-list"><a class="button secondary" href="./retrieval-word-templates.docx?v=3" download>All Word worksheets ↓</a><a class="button secondary" href="./retrieval-powerpoint-templates.pptx?v=3" download>All PowerPoint templates ↓</a><a class="button secondary" href="./retrieval-templates.zip?v=3" download>Download every template ↓</a></div></section>`;
    const search=document.getElementById('search'),time=document.getElementById('time'),group=document.getElementById('group'),prep=document.getElementById('prep');let filtered=[];
    function render(){const q=search.value.trim().toLowerCase();filtered=activities.filter(a=>[a.name,a.summary,a.materials,a.credit].join(' ').toLowerCase().includes(q)&&a.minutes<=Number(time.value)&&(!group.value||a.group===group.value)&&(!prep.value||a.prep===prep.value));document.getElementById('count').textContent=`${filtered.length} activities shown · ${selected.size} on your wheel`;document.getElementById('cards').innerHTML=filtered.length?filtered.map(card).join(''):'<p class="empty">No activities match these filters. Try more time or reset the filters.</p>';document.getElementById('use-filtered').disabled=!filtered.length;}
    [search,time,group,prep].forEach(el=>el.addEventListener('input',render));
    document.getElementById('cards').addEventListener('change',e=>{const id=e.target.dataset.select;if(!id)return;e.target.checked?selected.add(id):selected.delete(id);saveSelection();document.getElementById('count').textContent=`${filtered.length} activities shown · ${selected.size} on your wheel`;});
    document.getElementById('reset').onclick=()=>{search.value='';time.value='99';group.value='';prep.value='';render();};
    document.getElementById('use-filtered').onclick=()=>{selected=new Set(filtered.map(a=>a.id));saveSelection();render();};render();
  }
  if(document.body.dataset.page==='activity'){
    const a=activities.find(x=>x.id===document.body.dataset.activity);if(!a)return;
    main.innerHTML=`<a class="back" href="./retrieval-activities.html">← All activities</a><section class="activity-hero"><div><p class="eyebrow">ACTIVITY GUIDE</p><h1>${esc(a.name)}</h1><p class="lead">${esc(a.summary)}</p>${chips(a)}</div><div>${icon(a.icon)}</div></section><div class="guide-layout"><div><h2>How to run it</h2><ol class="steps">${a.steps.map((s,i)=>`<li class="step"><div class="step-visual">${icon(s.icon)}<span class="step-number">STEP 0${i+1}</span></div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p></li>`).join('')}</ol><section class="credit-note"><h2>Credits & source</h2><p>${esc(a.origin)}</p><a href="${esc(a.source)}" target="_blank" rel="noopener">${esc(a.credit)} ↗</a><p class="muted">Instructions and illustrations: TNT Teaching Tools. Suggested timings are flexible guidance.</p></section></div><aside class="guide-sidebar"><section><h2>Prepare</h2><p>${esc(a.materials)}</p><h2>Check learning</h2><p>${esc(a.check)}</p><h2>Adapt for your class</h2><p>${esc(a.adapt)}</p></section><section class="timer-section"><h2>Classroom timer</h2><span id="timer" class="timer" role="timer" aria-live="off">${String(a.minutes).padStart(2,'0')}:00</span><label>Minutes<input id="minutes" type="number" min="1" max="60" value="${a.minutes}"></label><div class="timer-controls"><button id="start-timer">Start</button><button class="secondary" id="reset-timer">Reset</button><button class="secondary" id="project">Project view</button></div><p id="timer-status" role="status" class="muted">Adjust for your class and include checking time.</p></section><section><h2>Editable templates</h2>${downloadLinks(a)}<p class="muted">Add your own topic, prompts and checked answers.</p><div class="actions"><button class="secondary" id="print">Print guide</button><button class="secondary" id="copy">Copy link</button></div><p id="copy-status" class="muted" role="status"></p></section></aside></div>`;
    const output=document.getElementById('timer'),field=document.getElementById('minutes'),start=document.getElementById('start-timer'),status=document.getElementById('timer-status');let remaining=a.minutes*60,interval=null,deadline=0;
    const display=()=>output.textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');
    const stop=()=>{clearInterval(interval);interval=null;start.textContent='Start';field.disabled=false;};
    function reset(){stop();let n=Math.max(1,Math.min(60,Number(field.value)||a.minutes));field.value=String(n);remaining=Math.round(n*60);display();status.textContent='Timer ready.';}
    start.onclick=()=>{if(interval){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));stop();display();start.textContent='Resume';status.textContent='Paused.';return;}if(!remaining)reset();deadline=Date.now()+remaining*1000;field.disabled=true;start.textContent='Pause';status.textContent='Timer running.';interval=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));display();if(!remaining){stop();status.textContent='Time is up. Check and improve your answers.';}},200);};
    field.onchange=reset;document.getElementById('reset-timer').onclick=reset;document.getElementById('project').onclick=e=>{document.body.classList.toggle('project-mode');e.target.textContent=document.body.classList.contains('project-mode')?'Exit project view':'Project view';};document.addEventListener('keydown',e=>{if(e.key==='Escape'){document.body.classList.remove('project-mode');document.getElementById('project').textContent='Project view';}});
    document.getElementById('print').onclick=()=>window.print();document.getElementById('copy').onclick=async()=>{const el=document.getElementById('copy-status');try{await navigator.clipboard.writeText(location.href);el.textContent='Activity link copied.';}catch{el.textContent='Copy the page address from your browser to share this activity.';}};
  }
  if(document.body.dataset.page==='wheel'){
    main.innerHTML=head('Spin for a fresh idea.','Choose the activities that suit your class, then let the wheel suggest a format. You decide which taught knowledge to revisit.')+`<div class="wheel-layout"><section class="wheel-stage"><div class="wheel-wrap"><span class="pointer" aria-hidden="true"></span><svg id="wheel-svg" viewBox="0 0 440 440" role="img" aria-label="Retrieval activity wheel"></svg></div><button id="spin">Spin the wheel</button><div id="result" class="wheel-result" role="status" aria-live="polite"><p>Select activities, then spin to see a suggestion and its guide.</p></div><div id="wheel-key" class="wheel-key"></div></section><section class="wheel-settings"><h2>Your wheel, your choice.</h2><p class="muted">Every selected activity has an equal chance. The wheel suggests the activity format, not a question.</p><div class="actions"><button id="all" class="secondary">Select all</button><button id="none" class="secondary">Clear selection</button></div><p id="wheel-count" class="muted" role="status"></p><div id="options" class="wheel-options"></div><a href="./retrieval-activities.html">Filter by time, grouping or preparation ↗</a><aside class="notice"><strong>Make a purposeful choice.</strong> Check materials and timing before starting. A random activity cannot guarantee useful retrieval or curriculum coverage.</aside></section></div>`;
    const svg=document.getElementById('wheel-svg'),spin=document.getElementById('spin'),result=document.getElementById('result');let pool=[],rotation=0,busy=false;
    document.getElementById('options').innerHTML=activities.map(a=>`<label class="wheel-option"><input type="checkbox" data-wheel="${a.id}" ${selected.has(a.id)?'checked':''}><span>${esc(a.name)}<br><small class="muted">${a.minutes} min · ${a.prep==='None'?'No':a.prep} prep</small></span></label>`).join('');
    function renderWheel(){pool=activities.filter(a=>selected.has(a.id));rotation=0;svg.style.transition='none';svg.style.transform='rotate(0deg)';document.getElementById('wheel-count').textContent=`${pool.length} activities selected`;spin.disabled=!pool.length;result.innerHTML='<p>'+(pool.length?'Ready to spin.':'Choose at least one activity to spin.')+'</p>';const colours=['#ffc928','#dcebc7','#f5c3a4','#b8dbd7','#f4e7b2','#d5d6ed'];const n=pool.length;let markup='';for(let i=0;i<n;i++){let s=i*2*Math.PI/n-Math.PI/2,e=(i+1)*2*Math.PI/n-Math.PI/2;const x=220+205*Math.cos(s),y=220+205*Math.sin(s),xe=220+205*Math.cos(e),ye=220+205*Math.sin(e);markup+=n===1?`<circle cx="220" cy="220" r="205" fill="${colours[0]}"/>`:`<path d="M220 220 L${x} ${y} A205 205 0 ${n===2?0:e-s>Math.PI?1:0} 1 ${xe} ${ye} Z" fill="${colours[i%colours.length]}" stroke="white" stroke-width="3"/>`;const mid=(s+e)/2;markup+=`<text x="${220+151*Math.cos(mid)}" y="${220+151*Math.sin(mid)}" text-anchor="middle" dominant-baseline="middle" fill="#242720" font-size="18" font-weight="700">${i+1}</text>`;}markup+='<circle cx="220" cy="220" r="48" fill="#242720"/><text x="220" y="225" text-anchor="middle" fill="#ffc928" font-size="20" font-weight="800">TNT</text>';svg.innerHTML=markup;document.getElementById('wheel-key').innerHTML=pool.map((a,i)=>`<span><strong>${i+1}.</strong> ${esc(a.name)}</span>`).join('');}
    function enableSettings(enabled){document.querySelectorAll('[data-wheel],#all,#none').forEach(el=>el.disabled=!enabled);}
    document.getElementById('options').onchange=e=>{if(busy)return;const id=e.target.dataset.wheel;if(!id)return;e.target.checked?selected.add(id):selected.delete(id);saveSelection();renderWheel();};
    for(const id of ['all','none'])document.getElementById(id).onclick=()=>{selected=new Set(id==='all'?activities.map(a=>a.id):[]);saveSelection();document.querySelectorAll('[data-wheel]').forEach(el=>el.checked=selected.has(el.dataset.wheel));renderWheel();};
    spin.onclick=()=>{if(busy||!pool.length)return;busy=true;spin.disabled=true;enableSettings(false);result.innerHTML='<p>Choosing an activity…</p>';const index=Math.floor(Math.random()*pool.length),a=pool[index],segment=360/pool.length,target=(360-(index+.5)*segment)%360;rotation+=360*5+((target-rotation%360+360)%360);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;svg.style.transition=reduced?'none':'transform 3s cubic-bezier(.15,.65,.15,1)';void svg.getBoundingClientRect();svg.style.transform=`rotate(${rotation}deg)`;setTimeout(()=>{result.innerHTML=`<h2>${esc(a.name)}</h2><p>${esc(a.summary)}</p>${chips(a)}<a class="button" href="./retrieval-${a.id}.html">Open the activity guide ↗</a>`;busy=false;spin.disabled=false;enableSettings(true);},reduced?0:3050);};renderWheel();
  }
})();
